Update documentation and move pre-requisites to the main README.md
Azure-Samples/java-ai pull request #15
Opened 2024-10-11 11:00 UTC by pmalarme

This pull request includes updates to the `README.md` files to improve clarity and provide additional resources for setting up the environment. The most important changes include adding a prerequisites section, enhancing the documentation with links to relevant resources, and removing redundant information.

Documentation updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R16-R24): Added a prerequisites section to guide users on setting up the necessary tools and environment.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L33-R49): Enhanced the resource list with links to relevant Azure documentation for easier access.

Redundant information removal:

* [`src/ai-image-processing-service/README.md`](diffhunk://#diff-29bfebf051e2581119c5f43637bfa28e2c182678c7e27312569a4ec494c4e762L13-L21): Removed the duplicated prerequisites section to avoid redundancy and maintain consistency.

2024-10-11 15:28 UTC, SandraAhlgrimm requested changes
Thank you.

Let's remove the localization from the links, so people get the documentation with their settings or based on their country.
And I've suggested a few minor changes.

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +- [Azure Container Apps Environment](https://learn.microsoft.com/en-us/azure/container-apps/)
```suggestion
- [Azure Container Apps Environment](https://learn.microsoft.com/azure/container-apps/)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +    - [Eureka Server for Spring Component](https://learn.microsoft.com/en-us/azure/container-apps/java-eureka-server-usage)
```suggestion
    - [Eureka Server for Spring Component](https://learn.microsoft.com/azure/container-apps/java-eureka-server-usage)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +    - [Admin for Spring Component](https://learn.microsoft.com/en-us/azure/container-apps/java-admin-for-spring-usage)
```suggestion
    - [Admin for Spring Component](https://learn.microsoft.com/azure/container-apps/java-admin-for-spring-usage)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +- [Azure Container Apps with Java Runtime](https://learn.microsoft.com/en-us/azure/container-apps/java-metrics)
```suggestion
- [Azure Container Apps with Java Runtime](https://learn.microsoft.com/azure/container-apps/java-metrics)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +- [Java 17+](https://learn.microsoft.com/en-us/java/openjdk/download)
```suggestion
- [Java 17+](https://learn.microsoft.com/java/openjdk/download)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +- [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
```suggestion
- [Azure CLI](https://docs.microsoft.com/cli/azure/install-azure-cli)
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +Easiest way to start is to [deploy a GitHub Codespace](https://github.com/codespaces/new/Azure-Samples/java-ai) as it contains all the prerequisites.
I think they'll have to Fork it first.

```suggestion
Easiest way to start is to Fork and [open the repository in a GitHub Codespace](https://github.com/codespaces/new/Azure-Samples/java-ai) as it contains all the prerequisites.
```

2024-10-11 15:28 UTC, SandraAhlgrimm commented on README.md
> +If you deploy locally, you need to have the following installed:
```suggestion
If you develop locally, you need to have the following installed:
```

2024-10-11 16:46 UTC, pmalarme commented
> Thank you.
> 
> Let's remove the localization from the links, so people get the documentation with their settings or based on their country. And I've suggested a few minor changes.

Done

2024-10-16 10:50 UTC, SandraAhlgrimm commented
Thank you!

2024-10-16 10:51 UTC, SandraAhlgrimm approved these changes

2024-10-21 13:59 UTC, merged