Trivial updates
Azure-Samples/java-ai pull request #30
Opened 2024-10-31 01:32 UTC by edburns

modified:   README.md

- This is a Spring app first and a Java app second. Let's just call it a Spring app.

modified:   infra/bicep/hooks/build-java.sh
modified:   infra/bicep/hooks/export-env.sh

- Must have changed by doing azd up.

modified:   src/ai-shop-ui/src/App.tsx

- Update URL to github repo.

2024-10-31 08:55 UTC, pmalarme requested changes
Hi Ed,

Thank you for your contribution. Please find some minor comments.

Kind regards,
Pierre

2024-10-31 08:55 UTC, pmalarme commented on README.md
> +This is a simple AI Shop application that demonstrates how to use Azure OpenAI with Spring to create a sample second hand shop. It uses the multi-modal capabilities of the OpenAI API to generate a de
I would keep Java as the goal is to add a micro-service in Quarkus

2024-10-31 08:55 UTC, pmalarme commented on infra/bicep/hooks/build-java.sh
Should not be part of the commit if there is no change.

2024-10-31 08:55 UTC, pmalarme commented on infra/bicep/hooks/export-env.sh
Should not be part of the commit if there is no change.

2024-11-06 19:09 UTC, SandraAhlgrimm commented
Thanks Ed, UI update is handled here https://github.com/Azure-Samples/java-ai/pull/36.
We'll stay with Java as the sample should receive at least one Quarkus and Semantic Kernel service in future.

2024-11-06 19:09 UTC, closed without merging