Improve the documentation
Azure-Samples/java-ai pull request #42
Opened 2024-12-18 16:41 UTC by ma3u

Thank you for the great AI example! 

 Here some suggestions to improve the documentation. So I hope the developer experience will be improved.

Related to issue
+ https://github.com/Azure-Samples/java-ai/issues/40

2025-01-09 09:22 UTC, SandraAhlgrimm requested changes
Hi @ma3u, thanks a lot for your PR and contribution!
I have some small suggestions and then lets merge it.

2025-01-09 09:22 UTC, SandraAhlgrimm commented on README.md
> +After approx 15mins all resources will be deployed. Please call the printed endpoint of the ai-shop-ui of the terminal in a browser. You should see the startpage of **The AI Shop**:
```suggestion
After up to 15 minutes all resources will be deployed. Please call the printed endpoint of the ai-shop-ui of the terminal in a browser. You should see the start page of **The AI Shop**:
```

2025-01-09 09:22 UTC, SandraAhlgrimm commented on README.md
> +Please upload a product picture to generate name, brand, model, price, description, categories via OpenAI.
```suggestion
Just upload a product picture to generate name, brand, model, price, description, categories via OpenAI.
```

2025-01-09 10:05 UTC, ma3u commented
@microsoft-github-policy-service agree

2025-02-06 19:09 UTC, SandraAhlgrimm approved these changes

2025-02-12 11:15 UTC, merged